<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['author', 'title', 'slug', 'content'];

//    public function getRouteKeyName()
//    {
//        //return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
//        //return 'slug';
//    }

    public function author()
    {
        return $this->belongsTo(User::class, 'author', 'id');
    }
}
